import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className + " flex h-screen w-screen flex-col divide-y"
        }
      >
        <header className=" flex h-16 flex-none items-center justify-center">
          header
        </header>
        <main className=" flex flex-grow">{children}</main>
        <footer className=" flex h-16 flex-none items-center justify-center">
          footer
        </footer>
      </body>
    </html>
  );
}
